### ISSUE TITLE
Rejecting re-init on previously-failed class java.lang.Class<com.baidu.android.pushservice.e$2>

### ISSUE THREAD

**Issue by shushil** [xyfoo/Baidu.Android.PushService#3]
Hello, I am trying to use this nuget package for my app for push notification in china with Azure Notification hub. I have integrated everything as the post suggested. I do get the channelId. However I am not receiving the push notification, Upon digging little deeper. I saw this error.

12-24 11:01:19.757 I/MainActivity(24574): Calling BaiduPushReceiver.
12-24 11:01:19.774 I/.baidu.demopus(24574): Rejecting re-init on previously-failed class java.lang.Class<com.baidu.android.pushservice.e$2>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coloros/mcssdk/callback/PushCallback;
12-24 11:01:19.775 I/.baidu.demopus(24574):   at boolean com.baidu.android.pushservice.e.l(android.content.Context) ((null):-1)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void com.baidu.android.pushservice.PushManager.startWork(android.content.Context, int, java.lang.String) ((null):-1)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.n_onResume() (MainActivity.java:-2)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.onResume() (MainActivity.java:41)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1412)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:7292)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3776)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, java.lang.String) (ActivityThread.java:3816)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:51)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:145)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:70)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.os.Looper.loop() (Looper.java:193)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 11:01:19.775 I/.baidu.demopus(24574):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
12-24 11:01:19.776 I/.baidu.demopus(24574): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.coloros.mcssdk.callback.PushCallback" on path: DexPathList[[zip file "/data/app/com.baidu.demopush-NmerScYXoj2C7-xioi3Scg==/base.apk"],nativeLibraryDirectories=[/data/app/com.baidu.demopush-NmerScYXoj2C7-xioi3Scg==/lib/x86, /data/app/com.baidu.demopush-NmerScYXoj2C7-xioi3Scg==/base.apk!/lib/x86, /system/lib]]
12-24 11:01:19.776 I/.baidu.demopus(24574):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at boolean com.baidu.android.pushservice.e.l(android.content.Context) ((null):-1)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void com.baidu.android.pushservice.PushManager.startWork(android.content.Context, int, java.lang.String) ((null):-1)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.n_onResume() (MainActivity.java:-2)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.onResume() (MainActivity.java:41)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1412)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:7292)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3776)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, java.lang.String) (ActivityThread.java:3816)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:51)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:145)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:70)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.os.Looper.loop() (Looper.java:193)
12-24 11:01:19.776 I/.baidu.demopus(24574):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
12-24 11:01:19.777 I/.baidu.demopus(24574):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 11:01:19.777 I/.baidu.demopus(24574):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
12-24 11:01:19.777 I/.baidu.demopus(24574):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
12-24 11:01:19.777 I/.baidu.demopus(24574): 
12-24 11:01:19.777 I/.baidu.demopus(24574): Rejecting re-init on previously-failed class java.lang.Class<com.baidu.android.pushservice.e$2>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coloros/mcssdk/callback/PushCallback;
12-24 11:01:19.777 I/.baidu.demopus(24574):   at boolean com.baidu.android.pushservice.e.l(android.content.Context) ((null):-1)
12-24 11:01:19.777 I/.baidu.demopus(24574):   at void com.baidu.android.pushservice.PushManager.startWork(android.content.Context, int, java.lang.String) ((null):-1)
12-24 11:01:19.777 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.n_onResume() (MainActivity.java:-2)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.onResume() (MainActivity.java:41)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1412)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:7292)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3776)
Thread started: <Thread Pool> #312-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, java.lang.String) (ActivityThread.java:3816)

12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:51)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:145)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:70)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.os.Looper.loop() (Looper.java:193)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
12-24 11:01:19.778 I/.baidu.demopus(24574):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
12-24 11:01:19.778 I/.baidu.demopus(24574): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.coloros.mcssdk.callback.PushCallback" on path: DexPathList[[zip file "/data/app/com.baidu.demopush-NmerScYXoj2C7-xioi3Scg==/base.apk"],nativeLibraryDirectories=[/data/app/com.baidu.demopush-NmerScYXoj2C7-xioi3Scg==/lib/x86, /data/app/com.baidu.demopush-NmerScYXoj2C7-xioi3Scg==/base.apk!/lib/x86, /system/lib]]
12-24 11:01:19.778 I/.baidu.demopus(24574):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
Thread started: <Thread Pool> #412-24 11:01:19.779 I/.baidu.demopus(24574):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)

12-24 11:01:19.779 I/.baidu.demopus(24574):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at boolean com.baidu.android.pushservice.e.l(android.content.Context) ((null):-1)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void com.baidu.android.pushservice.PushManager.startWork(android.content.Context, int, java.lang.String) ((null):-1)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.n_onResume() (MainActivity.java:-2)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void crc6449f0bdb02497717b.MainActivity.onResume() (MainActivity.java:41)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1412)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:7292)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3776)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, java.lang.String) (ActivityThread.java:3816)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:51)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:145)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:70)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
Thread started: <Thread Pool> #512-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)

12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.os.Looper.loop() (Looper.java:193)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
12-24 11:01:19.779 I/.baidu.demopus(24574):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 11:01:19.780 I/.baidu.demopus(24574):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
12-24 11:01:19.780 I/.baidu.demopus(24574):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
12-24 11:01:19.780 I/.baidu.demopus(24574): 
12-24 11:01:20.090 W/DeviceId(24574): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
12-24 11:01:20.090 I/chatty  (24574): uid=10073(com.baidu.demopush) ModeConfig-upda identical 1 line
12-24 11:01:20.090 W/DeviceId(24574): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
12-24 11:01:20.114 E/DeviceId(24574): Read IMEI failed
12-24 11:01:20.114 E/DeviceId(24574): java.lang.SecurityException: getDeviceId
12-24 11:01:20.114 E/DeviceId(24574): 	at android.os.Parcel.createException(Parcel.java:1942)
12-24 11:01:20.114 E/DeviceId(24574): 	at android.os.Parcel.readException(Parcel.java:1910)
12-24 11:01:20.114 E/DeviceId(24574): 	at android.os.Parcel.readException(Parcel.java:1860)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5398)
12-24 11:01:20.114 E/DeviceId(24574): 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1240)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.h(Unknown Source:13)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.d(Unknown Source:21)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.b(Unknown Source:251)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.d(Unknown Source:19)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.a(Unknown Source:0)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.b.e$1.a(Unknown Source:235)
12-24 11:01:20.114 E/DeviceId(24574): 	at com.baidu.android.pushservice.h.c.run(Unknown Source:17)
12-24 11:01:20.114 E/DeviceId(24574): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
12-24 11:01:20.114 E/DeviceId(24574): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-24 11:01:20.114 E/DeviceId(24574): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-24 11:01:20.114 E/DeviceId(24574): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-24 11:01:20.114 E/DeviceId(24574): 	at java.lang.Thread.run(Thread.java:764)
12-24 11:01:20.137 E/DeviceId(24574): Read IMEI failed
12-24 11:01:20.137 E/DeviceId(24574): java.lang.SecurityException: getDeviceId
12-24 11:01:20.137 E/DeviceId(24574): 	at android.os.Parcel.createException(Parcel.java:1942)
12-24 11:01:20.137 E/DeviceId(24574): 	at android.os.Parcel.readException(Parcel.java:1910)
12-24 11:01:20.137 E/DeviceId(24574): 	at android.os.Parcel.readException(Parcel.java:1860)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5398)
12-24 11:01:20.137 E/DeviceId(24574): 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1240)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.h(Unknown Source:13)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.b(Unknown Source:288)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.d(Unknown Source:19)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.baidu.android.pushservice.j.e.a(Unknown Source:0)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.baidu.android.pushservice.b.e$1.a(Unknown Source:235)
12-24 11:01:20.137 E/DeviceId(24574): 	at com.baidu.android.pushservice.h.c.run(Unknown Source:17)
12-24 11:01:20.137 E/DeviceId(24574): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
12-24 11:01:20.137 E/DeviceId(24574): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-24 11:01:20.137 E/DeviceId(24574): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)Thread started: <Thread Pool> #6

12-24 11:01:20.137 E/DeviceId(24574): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-24 11:01:20.137 E/DeviceId(24574): 	at java.lang.Thread.run(Thread.java:764)

I am not being able to fix this. Can you provide me with some suggestion.
Thank you very much for creating this nuget package.

**Comment by rimuweinuan** [comment]
1. 下载最新的sdk：http://push.baidu.com/sdk/push_client_sdk_for_android
2.下载的内容里，将libs里面的jar包、so包复制替换原有工程里面
3.下载的内容里，根据docs/升级指南.pdf对项目中AndroidManifest.xml修改
4.如果还有类找不到的话，可以参考Demo/PushDemo_AS

**Comment by xyfoo** [comment]
@shushil : It's been some time since I've worked on this repo. The Baidu SDK v6.5.0.75 will attempt to run some OEM specific optimization code, without cross-checking if the device-in-question is on the list.

So the error log you're providing is indicating the SDK could not run some optimization code specific to device made by OPPO (see ```Lcom/coloros/mcssdk/callback/PushCallback``` - ColorOS is the OS for OPPO devices). If you're running on non-OPPO devices, you could safely ignore it.

As for why you could not retrieve the channel Id, maybe you should check out this issue #2 . And also please take note on the quirks as listed [here](https://github.com/xyfoo/Baidu.Android.PushService/wiki/Quirks).
